monitor = eDP-1, preferred, 0x0, 2
monitor = DP-1, preferred, auto-left, auto
monitor = DP-2, preferred, auto-left, auto
monitor = DP-3, preferred, auto-left, auto

xwayland {
    force_zero_scaling = true
}

env = GDK_SCALE,2

workspace = 5, monitor:DP-1, default:true
