input-field {
    placeholder_text = Who goes there?
    fade_on_empty = false

    position = 0, -20
    halign = center
    valign = center
    size = 20%, 5%

    outline_thickness = 3
    rounding = 12
    inner_color = rgba(181825ff)
    outer_color = rgba(6c7086ff)
    check_color = rgba(cba6f7ff)
    fail_color = rgba(f38ba8ff)

    font_color = rgba(cdd6f4ff)
    font_family = Fira Code
}

label {
    text = cmd[update:1000] echo "$(date +%R:%S)"
    font_size = 20
    
    position = -20, 20
    halign = right
    valign = bottom
}

label {
    text = $LAYOUT
    font_size = 20

    position = -20, 60
    halign = right
    valign = bottom
}

background {
    path = /home/itsmexxie/.config/wallpapers/david-revoy-01.jpg
    blur_passes = 2
}
